### ISSUE TITLE
plugin breaks replies in channels where you are effected by slowmode

### ISSUE THREAD

**Issue by CodeF53** [SammCheese/Do-Not-Slowmode-Me#2]
https://user-images.githubusercontent.com/37855219/178337667-0765cc2f-32a9-4e38-a1e8-11cb85b146eb.mp4

**Comment by SammCheese** [comment]
pog

**Comment by Ran-Mewo** [comment]
So is this going to be fixed?

**Comment by SammCheese** [comment]
Probably

**Comment by CodeF53** [comment]
RIP powercord, probably wont be fixed.

**Comment by Ran-Mewo** [comment]
Probably will be fixed*
